# Generated by Django 3.2.20 on 2023-07-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='time',
            field=models.CharField(max_length=5),
        ),
    ]
