# Generated by Django 3.2.20 on 2023-07-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_tour_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='time',
            new_name='meeting_time',
        ),
    ]
