# Generated by Django 3.2.20 on 2023-07-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_time_tour_meeting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.FloatField(blank=True, default=5),
            preserve_default=False,
        ),
    ]
