# Generated by Django 3.2.20 on 2023-07-31 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watchAgain',
            new_name='recommend',
        ),
    ]
